In [1]:
import os
import pandas as pd

In [2]:
df = pd.read_excel('1963-2021.xls')
df

,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,Tuition and required fees\2\,NaN,NaN,Year and control of institution,Tuition and required fees\2\,NaN,NaN,Year and control of institution,NaN,NaN,NaN
1,NaN,All insti-tutions,4-year,2-year,NaN,All insti-tutions,4-year,2-year,NaN,Tuition and required fees\2\,NaN,NaN
2,All institutions,NaN,NaN,NaN,Public insti-\n tutions,NaN,NaN,NaN,Private \n nonprofit and\n for-profit\n ...,NaN,NaN,NaN
3,1963,508.247693,552.578415,171.248587,1963-64,234,243.335845,97,1963-64,1012,1010.793127,642.000000
4,1968,596.33194,683.28882,250.398012,1968-69,295,321.002362,170,1968-69,1383,1417.128497,956.000000
5,1969,645.14035,755.008039,247.442178,1969-70,323,358.354832,178,1969-70,1533,1561.856645,1034.000000
6,1970,688.022348,813.787615,249.443912,1970-71,351,393.688558,187,1970-71,1684,1706.297804,1109.000000
7,1971,723.809897,865.335956,250.819498,1971-72,376,427.761617,192,1971-72,1820,1832.157556,1172.000000
8,1972,759.453412,950.341047,286.849359,1972-73,407,502.630045,233,1972-73,1898,1948.308052,1221.000000
9,1973,795.652682,984.584412,328.4664,1973-74,438,513.576856,274,1973-74,1989,2044.526495,1303.000000
10,1974,809.364873,1008.081943,327.613386,1974-75,432,512.416445,277,1974-75,2117,2130.384526,1367.000000
11,1975,829.06063,1073.14284,297.20822,1975-76,433,542.145427,245,1975-76,2272,2291.253118,1427.000000
12,1976,924.047974,1218.395943,345.559064,1976-77,478.653052,616.551537,283.434414,1976-77,2466.704551,2534.024033,1592.000000
13,1977,984.468427,1291.480089,378.183622,1977-78,511.582393,654.680963,306.443288,1977-78,2623.710475,2700.299029,1705.508579
14,1978,1072.651823,1396.738515,410.890811,1978-79,542.744293,687.674475,327.249268,1978-79,2867.495398,2957.923714,1830.798275
15,1979,1162.820372,1512.942416,450.970073,1979-80,583.400447,737.548351,354.811219,1979-80,3130.07446,3225.038907,2061.724600
16,1980,1288.61468,1678.65689,525.897248,1980-81,634.883778,803.747278,391.126587,1980-81,3497.920622,3616.835567,2412.952903
17,1981,1456.644001,1907.23353,589.5819,1981-82,713.782805,909.499354,434.496098,1981-82,3952.592794,4113.319087,2604.746018
18,1982,1625.825136,2139.37219,674.635969,1982-83,798.193283,1031.433165,473,1982-83,4438.847316,4638.918917,3008.000000
19,1983,1782.679703,2343.561612,730.287231,1983-84,891.397517,1147.727212,528,1983-84,4850.57083,5092.950750,3099.000000
20,1984,1985.30247,2567.45309,821.156525,1984-85,970.773316,1227.881695,584,1984-85,5314.528636,5555.859459,3485.000000
21,1985,2181.044843,2784.360136,888.453668,1985-86\5\,1044.717185,1317.601053,641,1985-86\5\,5788.795717,6120.558325,3672.000000
22,1986,2312.012293,3042.129851,897.220056,1986-87,1106.178294,1413.678767,660.409206,1986-87,6315.774966,6658.444594,3683.686476
23,1987,2458.016007,3200.840732,809.207474,1987-88,1218.267898,1537.368133,705.847334,1987-88,6988.310506,7116.105052,4160.940531
24,1988,2657.576906,3472.202586,979.445506,1988-89,1284.709835,1646.188102,730.025178,1988-89,7461.056967,7721.603549,4817.440656
25,1989,2839.240669,3800.185802,977.797578,1989-90,1356.003276,1779.609033,756.057063,1989-90,8147.205645,8396.328498,5196.284765
26,1990,3016.257316,4008.926979,1087.476484,1990-91,1453.966107,1888.129113,824.098974,1990-91,8772.27253,9082.536420,5570.020600
27,1991,3285.502385,4385.330772,1189.192872,1991-92,1627.952451,2116.892852,936.330522,1991-92,9419.408483,9759.443078,5754.131164
28,1992,3517.14546,4751.943402,1275.659349,1992-93,1781.521371,2349.108575,1025.192532,1992-93,9941.640968,10293.533165,6058.846392
29,1993,3827.248565,5119.05172,1398.702351,1993-94,1942.064502,2536.582308,1124.661292,1993-94,10571.697928,10952.218450,6369.949367
30,1994,4044.473061,5390.869311,1487.617175,1994-95,2056.899043,2680.715293,1192.493385,1994-95,11110.809362,11480.931134,6914.191864
31,1995,4338.036789,5785.913038,1522.237449,1995-96,2178.722424,2847.579122,1239.361067,1995-96,11864.268771,12243.156323,7094.491118
32,1996,4564.119655,6118.454397,1543.00768,1996-97,2271.434885,2987.221282,1275.860064,1996-97,12497.860142,12881.247323,7236.205530
33,1997,4754.786177,6350.50261,1694.522015,1997-98,2360.436365,3109.505876,1314.050935,1997-98,12800.669159,13344.249780,7464.339708
34,1998,5012.959591,6722.746145,1725.29603,1998-99,2430.142559,3228.716855,1326.54294,1998-99,13428.223977,13972.870964,7853.512371
35,1999,5221.805277,7040.388512,1727.828462,1999-2000,2503.523724,3348.805705,1347.720361,1999-2000,14100.175042,14616.047633,8224.904918
36,2000,5377.192077,7371.534728,1698.142352,2000-01,2562.051353,3500.524982,1332.567301,2000-01,15000.344423,15470.473798,9066.709337
37,2001,5646.498458,7786.04322,1799.736397,2001-02,2700.190067,3735.205656,1379.761307,2001-02,15742.182562,16210.886963,10076.229950
38,2002,6002.190321,8308.530615,1903.261001,2002-03,2902.621187,4046.173101,1483.025331,2002-03,16382.648687,16825.894536,10650.828366
39,2003,6608.017678,9028.81673,2174.481686,2003-04,3318.720504,4586.540638,1701.983005,2003-04,17314.683822,17763.195261,11545.493938
40,2004,7122.104862,9705.85311,2337.854882,2004-05,3629.187528,5026.550249,1848.698481,2004-05,18153.847528,18603.887093,12122.062427
41,2005,7601.498252,10278.859334,2416.88942,2005-06,3873.522389,5350.929386,1935.073249,2005-06,18862.399712,19291.662562,12449.857309
42,2006,8093.013354,10930.695048,2495.958137,2006-07,4102.129261,5666.216013,2017.444817,2006-07,20046.780792,20516.598712,12707.743906
43,2007,8480.061648,11454.965114,2516.003231,2007-08,4287.832579,5943.137008,2058.483415,2007-08,20972.358612,21426.674228,13127.857658
44,2008,8892.214382,12045.665304,2616.982346,2008-09,4511.831708,6311.838371,2135.679321,2008-09,21575.128373,22039.916813,13566.840224
45,2009,9134.578253,12404.140141,2923.19754,2009-10,4763.22675,6716.599169,2283.178435,2009-10,21763.8709,22269.293952,14862.485290
46,2010,9574.953288,12945.422892,3059.651545,2010-11,5074.956673,7131.846567,2440.90596,2010-11,22041.510842,22677.294091,13687.420301
47,2011,10178.58778,13571.989221,3244.166435,2011-12,5563.276164,7713.410494,2651.129593,2011-12,22850.496962,23463.672108,13961.426384
48,2012,10681.054267,14099.410556,3321.512871,2012-13,5898.582322,8070.190026,2791.615629,2012-13,23943.465789,24522.636955,14149.279234
49,2013,11072.850667,14562.538031,3369.076366,2013-14,6120.285413,8311.861658,2880.516247,2013-14,25109.989556,25706.763577,14170.369324
50,2014,11487.340682,14956.779315,3389.24375,2014-15,6370.29977,8543.353275,2954.685406,2014-15,26181.644638,26738.523395,14261.112059
51,2015,11861.804652,15342.950775,3411.687366,2015-16,6611.744095,8778.397073,3037.735875,2015-16,27436.353797,27941.604628,14527.602406
52,2016,12218.922307,15511.775185,3518.860056,2016-17,6817.93524,8804.399324,3156.432123,2016-17,28944.712039,29475.543676,14589.112198
53,2017,12612.914604,15923.190428,3537.422377,2017-18,7051.453334,9036.059338,3241.674326,2017-18,30274.253931,30722.613119,14893.891563
54,2018,13011.776185,16315.932682,3562.902945,2018-19,7247.948811,9211.803768,3312.17949,2018-19,31526.90246,31883.340470,15720.207014
55,2019,13359.762496,16646.458769,3621.67203,2019-20,7410.340752,9349.141651,3376.908301,2019-20,32411.08598,32763.973541,15830.983966
56,2020,13677.415717,16618.293165,3780.726037,2020-21,7637.562733,9374.523538,3501.349412,2020-21,32444.336024,32825.296451,15473.835801
57,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
pd.set_option('display.max_rows', None)
df

,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,Tuition and required fees\2\,NaN,NaN,Year and control of institution,Tuition and required fees\2\,NaN,NaN,Year and control of institution,NaN,NaN,NaN
1,NaN,All insti-tutions,4-year,2-year,NaN,All insti-tutions,4-year,2-year,NaN,Tuition and required fees\2\,NaN,NaN
2,All institutions,NaN,NaN,NaN,Public insti-\n tutions,NaN,NaN,NaN,Private \n nonprofit and\n for-profit\n ...,NaN,NaN,NaN
3,1963,508.247693,552.578415,171.248587,1963-64,234,243.335845,97,1963-64,1012,1010.793127,642.000000
4,1968,596.33194,683.28882,250.398012,1968-69,295,321.002362,170,1968-69,1383,1417.128497,956.000000
5,1969,645.14035,755.008039,247.442178,1969-70,323,358.354832,178,1969-70,1533,1561.856645,1034.000000
6,1970,688.022348,813.787615,249.443912,1970-71,351,393.688558,187,1970-71,1684,1706.297804,1109.000000
7,1971,723.809897,865.335956,250.819498,1971-72,376,427.761617,192,1971-72,1820,1832.157556,1172.000000
8,1972,759.453412,950.341047,286.849359,1972-73,407,502.630045,233,1972-73,1898,1948.308052,1221.000000
9,1973,795.652682,984.584412,328.4664,1973-74,438,513.576856,274,1973-74,1989,2044.526495,1303.000000
10,1974,809.364873,1008.081943,327.613386,1974-75,432,512.416445,277,1974-75,2117,2130.384526,1367.000000
11,1975,829.06063,1073.14284,297.20822,1975-76,433,542.145427,245,1975-76,2272,2291.253118,1427.000000
12,1976,924.047974,1218.395943,345.559064,1976-77,478.653052,616.551537,283.434414,1976-77,2466.704551,2534.024033,1592.000000
13,1977,984.468427,1291.480089,378.183622,1977-78,511.582393,654.680963,306.443288,1977-78,2623.710475,2700.299029,1705.508579
14,1978,1072.651823,1396.738515,410.890811,1978-79,542.744293,687.674475,327.249268,1978-79,2867.495398,2957.923714,1830.798275
15,1979,1162.820372,1512.942416,450.970073,1979-80,583.400447,737.548351,354.811219,1979-80,3130.07446,3225.038907,2061.724600
16,1980,1288.61468,1678.65689,525.897248,1980-81,634.883778,803.747278,391.126587,1980-81,3497.920622,3616.835567,2412.952903
17,1981,1456.644001,1907.23353,589.5819,1981-82,713.782805,909.499354,434.496098,1981-82,3952.592794,4113.319087,2604.746018
18,1982,1625.825136,2139.37219,674.635969,1982-83,798.193283,1031.433165,473,1982-83,4438.847316,4638.918917,3008.000000
19,1983,1782.679703,2343.561612,730.287231,1983-84,891.397517,1147.727212,528,1983-84,4850.57083,5092.950750,3099.000000
20,1984,1985.30247,2567.45309,821.156525,1984-85,970.773316,1227.881695,584,1984-85,5314.528636,5555.859459,3485.000000
21,1985,2181.044843,2784.360136,888.453668,1985-86\5\,1044.717185,1317.601053,641,1985-86\5\,5788.795717,6120.558325,3672.000000
22,1986,2312.012293,3042.129851,897.220056,1986-87,1106.178294,1413.678767,660.409206,1986-87,6315.774966,6658.444594,3683.686476
23,1987,2458.016007,3200.840732,809.207474,1987-88,1218.267898,1537.368133,705.847334,1987-88,6988.310506,7116.105052,4160.940531
24,1988,2657.576906,3472.202586,979.445506,1988-89,1284.709835,1646.188102,730.025178,1988-89,7461.056967,7721.603549,4817.440656
25,1989,2839.240669,3800.185802,977.797578,1989-90,1356.003276,1779.609033,756.057063,1989-90,8147.205645,8396.328498,5196.284765
26,1990,3016.257316,4008.926979,1087.476484,1990-91,1453.966107,1888.129113,824.098974,1990-91,8772.27253,9082.536420,5570.020600
27,1991,3285.502385,4385.330772,1189.192872,1991-92,1627.952451,2116.892852,936.330522,1991-92,9419.408483,9759.443078,5754.131164
28,1992,3517.14546,4751.943402,1275.659349,1992-93,1781.521371,2349.108575,1025.192532,1992-93,9941.640968,10293.533165,6058.846392
29,1993,3827.248565,5119.05172,1398.702351,1993-94,1942.064502,2536.582308,1124.661292,1993-94,10571.697928,10952.218450,6369.949367
30,1994,4044.473061,5390.869311,1487.617175,1994-95,2056.899043,2680.715293,1192.493385,1994-95,11110.809362,11480.931134,6914.191864
31,1995,4338.036789,5785.913038,1522.237449,1995-96,2178.722424,2847.579122,1239.361067,1995-96,11864.268771,12243.156323,7094.491118
32,1996,4564.119655,6118.454397,1543.00768,1996-97,2271.434885,2987.221282,1275.860064,1996-97,12497.860142,12881.247323,7236.205530
33,1997,4754.786177,6350.50261,1694.522015,1997-98,2360.436365,3109.505876,1314.050935,1997-98,12800.669159,13344.249780,7464.339708
34,1998,5012.959591,6722.746145,1725.29603,1998-99,2430.142559,3228.716855,1326.54294,1998-99,13428.223977,13972.870964,7853.512371
35,1999,5221.805277,7040.388512,1727.828462,1999-2000,2503.523724,3348.805705,1347.720361,1999-2000,14100.175042,14616.047633,8224.904918
36,2000,5377.192077,7371.534728,1698.142352,2000-01,2562.051353,3500.524982,1332.567301,2000-01,15000.344423,15470.473798,9066.709337
37,2001,5646.498458,7786.04322,1799.736397,2001-02,2700.190067,3735.205656,1379.761307,2001-02,15742.182562,16210.886963,10076.229950
38,2002,6002.190321,8308.530615,1903.261001,2002-03,2902.621187,4046.173101,1483.025331,2002-03,16382.648687,16825.894536,10650.828366
39,2003,6608.017678,9028.81673,2174.481686,2003-04,3318.720504,4586.540638,1701.983005,2003-04,17314.683822,17763.195261,11545.493938
40,2004,7122.104862,9705.85311,2337.854882,2004-05,3629.187528,5026.550249,1848.698481,2004-05,18153.847528,18603.887093,12122.062427
41,2005,7601.498252,10278.859334,2416.88942,2005-06,3873.522389,5350.929386,1935.073249,2005-06,18862.399712,19291.662562,12449.857309
42,2006,8093.013354,10930.695048,2495.958137,2006-07,4102.129261,5666.216013,2017.444817,2006-07,20046.780792,20516.598712,12707.743906
43,2007,8480.061648,11454.965114,2516.003231,2007-08,4287.832579,5943.137008,2058.483415,2007-08,20972.358612,21426.674228,13127.857658
44,2008,8892.214382,12045.665304,2616.982346,2008-09,4511.831708,6311.838371,2135.679321,2008-09,21575.128373,22039.916813,13566.840224
45,2009,9134.578253,12404.140141,2923.19754,2009-10,4763.22675,6716.599169,2283.178435,2009-10,21763.8709,22269.293952,14862.485290
46,2010,9574.953288,12945.422892,3059.651545,2010-11,5074.956673,7131.846567,2440.90596,2010-11,22041.510842,22677.294091,13687.420301
47,2011,10178.58778,13571.989221,3244.166435,2011-12,5563.276164,7713.410494,2651.129593,2011-12,22850.496962,23463.672108,13961.426384
48,2012,10681.054267,14099.410556,3321.512871,2012-13,5898.582322,8070.190026,2791.615629,2012-13,23943.465789,24522.636955,14149.279234
49,2013,11072.850667,14562.538031,3369.076366,2013-14,6120.285413,8311.861658,2880.516247,2013-14,25109.989556,25706.763577,14170.369324
50,2014,11487.340682,14956.779315,3389.24375,2014-15,6370.29977,8543.353275,2954.685406,2014-15,26181.644638,26738.523395,14261.112059
51,2015,11861.804652,15342.950775,3411.687366,2015-16,6611.744095,8778.397073,3037.735875,2015-16,27436.353797,27941.604628,14527.602406
52,2016,12218.922307,15511.775185,3518.860056,2016-17,6817.93524,8804.399324,3156.432123,2016-17,28944.712039,29475.543676,14589.112198
53,2017,12612.914604,15923.190428,3537.422377,2017-18,7051.453334,9036.059338,3241.674326,2017-18,30274.253931,30722.613119,14893.891563
54,2018,13011.776185,16315.932682,3562.902945,2018-19,7247.948811,9211.803768,3312.17949,2018-19,31526.90246,31883.340470,15720.207014
55,2019,13359.762496,16646.458769,3621.67203,2019-20,7410.340752,9349.141651,3376.908301,2019-20,32411.08598,32763.973541,15830.983966
56,2020,13677.415717,16618.293165,3780.726037,2020-21,7637.562733,9374.523538,3501.349412,2020-21,32444.336024,32825.296451,15473.835801
57,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns = [1,2,3,4,5,6,7,8,9,10,11,12]
df

,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,Tuition and required fees\2\,NaN,NaN,Year and control of institution,Tuition and required fees\2\,NaN,NaN,Year and control of institution,NaN,NaN,NaN
1,NaN,All insti-tutions,4-year,2-year,NaN,All insti-tutions,4-year,2-year,NaN,Tuition and required fees\2\,NaN,NaN
2,All institutions,NaN,NaN,NaN,Public insti-\n tutions,NaN,NaN,NaN,Private \n nonprofit and\n for-profit\n ...,NaN,NaN,NaN
3,1963,508.247693,552.578415,171.248587,1963-64,234,243.335845,97,1963-64,1012,1010.793127,642.000000
4,1968,596.33194,683.28882,250.398012,1968-69,295,321.002362,170,1968-69,1383,1417.128497,956.000000
5,1969,645.14035,755.008039,247.442178,1969-70,323,358.354832,178,1969-70,1533,1561.856645,1034.000000
6,1970,688.022348,813.787615,249.443912,1970-71,351,393.688558,187,1970-71,1684,1706.297804,1109.000000
7,1971,723.809897,865.335956,250.819498,1971-72,376,427.761617,192,1971-72,1820,1832.157556,1172.000000
8,1972,759.453412,950.341047,286.849359,1972-73,407,502.630045,233,1972-73,1898,1948.308052,1221.000000
9,1973,795.652682,984.584412,328.4664,1973-74,438,513.576856,274,1973-74,1989,2044.526495,1303.000000
10,1974,809.364873,1008.081943,327.613386,1974-75,432,512.416445,277,1974-75,2117,2130.384526,1367.000000
11,1975,829.06063,1073.14284,297.20822,1975-76,433,542.145427,245,1975-76,2272,2291.253118,1427.000000
12,1976,924.047974,1218.395943,345.559064,1976-77,478.653052,616.551537,283.434414,1976-77,2466.704551,2534.024033,1592.000000
13,1977,984.468427,1291.480089,378.183622,1977-78,511.582393,654.680963,306.443288,1977-78,2623.710475,2700.299029,1705.508579
14,1978,1072.651823,1396.738515,410.890811,1978-79,542.744293,687.674475,327.249268,1978-79,2867.495398,2957.923714,1830.798275
15,1979,1162.820372,1512.942416,450.970073,1979-80,583.400447,737.548351,354.811219,1979-80,3130.07446,3225.038907,2061.724600
16,1980,1288.61468,1678.65689,525.897248,1980-81,634.883778,803.747278,391.126587,1980-81,3497.920622,3616.835567,2412.952903
17,1981,1456.644001,1907.23353,589.5819,1981-82,713.782805,909.499354,434.496098,1981-82,3952.592794,4113.319087,2604.746018
18,1982,1625.825136,2139.37219,674.635969,1982-83,798.193283,1031.433165,473,1982-83,4438.847316,4638.918917,3008.000000
19,1983,1782.679703,2343.561612,730.287231,1983-84,891.397517,1147.727212,528,1983-84,4850.57083,5092.950750,3099.000000
20,1984,1985.30247,2567.45309,821.156525,1984-85,970.773316,1227.881695,584,1984-85,5314.528636,5555.859459,3485.000000
21,1985,2181.044843,2784.360136,888.453668,1985-86\5\,1044.717185,1317.601053,641,1985-86\5\,5788.795717,6120.558325,3672.000000
22,1986,2312.012293,3042.129851,897.220056,1986-87,1106.178294,1413.678767,660.409206,1986-87,6315.774966,6658.444594,3683.686476
23,1987,2458.016007,3200.840732,809.207474,1987-88,1218.267898,1537.368133,705.847334,1987-88,6988.310506,7116.105052,4160.940531
24,1988,2657.576906,3472.202586,979.445506,1988-89,1284.709835,1646.188102,730.025178,1988-89,7461.056967,7721.603549,4817.440656
25,1989,2839.240669,3800.185802,977.797578,1989-90,1356.003276,1779.609033,756.057063,1989-90,8147.205645,8396.328498,5196.284765
26,1990,3016.257316,4008.926979,1087.476484,1990-91,1453.966107,1888.129113,824.098974,1990-91,8772.27253,9082.536420,5570.020600
27,1991,3285.502385,4385.330772,1189.192872,1991-92,1627.952451,2116.892852,936.330522,1991-92,9419.408483,9759.443078,5754.131164
28,1992,3517.14546,4751.943402,1275.659349,1992-93,1781.521371,2349.108575,1025.192532,1992-93,9941.640968,10293.533165,6058.846392
29,1993,3827.248565,5119.05172,1398.702351,1993-94,1942.064502,2536.582308,1124.661292,1993-94,10571.697928,10952.218450,6369.949367
30,1994,4044.473061,5390.869311,1487.617175,1994-95,2056.899043,2680.715293,1192.493385,1994-95,11110.809362,11480.931134,6914.191864
31,1995,4338.036789,5785.913038,1522.237449,1995-96,2178.722424,2847.579122,1239.361067,1995-96,11864.268771,12243.156323,7094.491118
32,1996,4564.119655,6118.454397,1543.00768,1996-97,2271.434885,2987.221282,1275.860064,1996-97,12497.860142,12881.247323,7236.205530
33,1997,4754.786177,6350.50261,1694.522015,1997-98,2360.436365,3109.505876,1314.050935,1997-98,12800.669159,13344.249780,7464.339708
34,1998,5012.959591,6722.746145,1725.29603,1998-99,2430.142559,3228.716855,1326.54294,1998-99,13428.223977,13972.870964,7853.512371
35,1999,5221.805277,7040.388512,1727.828462,1999-2000,2503.523724,3348.805705,1347.720361,1999-2000,14100.175042,14616.047633,8224.904918
36,2000,5377.192077,7371.534728,1698.142352,2000-01,2562.051353,3500.524982,1332.567301,2000-01,15000.344423,15470.473798,9066.709337
37,2001,5646.498458,7786.04322,1799.736397,2001-02,2700.190067,3735.205656,1379.761307,2001-02,15742.182562,16210.886963,10076.229950
38,2002,6002.190321,8308.530615,1903.261001,2002-03,2902.621187,4046.173101,1483.025331,2002-03,16382.648687,16825.894536,10650.828366
39,2003,6608.017678,9028.81673,2174.481686,2003-04,3318.720504,4586.540638,1701.983005,2003-04,17314.683822,17763.195261,11545.493938
40,2004,7122.104862,9705.85311,2337.854882,2004-05,3629.187528,5026.550249,1848.698481,2004-05,18153.847528,18603.887093,12122.062427
41,2005,7601.498252,10278.859334,2416.88942,2005-06,3873.522389,5350.929386,1935.073249,2005-06,18862.399712,19291.662562,12449.857309
42,2006,8093.013354,10930.695048,2495.958137,2006-07,4102.129261,5666.216013,2017.444817,2006-07,20046.780792,20516.598712,12707.743906
43,2007,8480.061648,11454.965114,2516.003231,2007-08,4287.832579,5943.137008,2058.483415,2007-08,20972.358612,21426.674228,13127.857658
44,2008,8892.214382,12045.665304,2616.982346,2008-09,4511.831708,6311.838371,2135.679321,2008-09,21575.128373,22039.916813,13566.840224
45,2009,9134.578253,12404.140141,2923.19754,2009-10,4763.22675,6716.599169,2283.178435,2009-10,21763.8709,22269.293952,14862.485290
46,2010,9574.953288,12945.422892,3059.651545,2010-11,5074.956673,7131.846567,2440.90596,2010-11,22041.510842,22677.294091,13687.420301
47,2011,10178.58778,13571.989221,3244.166435,2011-12,5563.276164,7713.410494,2651.129593,2011-12,22850.496962,23463.672108,13961.426384
48,2012,10681.054267,14099.410556,3321.512871,2012-13,5898.582322,8070.190026,2791.615629,2012-13,23943.465789,24522.636955,14149.279234
49,2013,11072.850667,14562.538031,3369.076366,2013-14,6120.285413,8311.861658,2880.516247,2013-14,25109.989556,25706.763577,14170.369324
50,2014,11487.340682,14956.779315,3389.24375,2014-15,6370.29977,8543.353275,2954.685406,2014-15,26181.644638,26738.523395,14261.112059
51,2015,11861.804652,15342.950775,3411.687366,2015-16,6611.744095,8778.397073,3037.735875,2015-16,27436.353797,27941.604628,14527.602406
52,2016,12218.922307,15511.775185,3518.860056,2016-17,6817.93524,8804.399324,3156.432123,2016-17,28944.712039,29475.543676,14589.112198
53,2017,12612.914604,15923.190428,3537.422377,2017-18,7051.453334,9036.059338,3241.674326,2017-18,30274.253931,30722.613119,14893.891563
54,2018,13011.776185,16315.932682,3562.902945,2018-19,7247.948811,9211.803768,3312.17949,2018-19,31526.90246,31883.340470,15720.207014
55,2019,13359.762496,16646.458769,3621.67203,2019-20,7410.340752,9349.141651,3376.908301,2019-20,32411.08598,32763.973541,15830.983966
56,2020,13677.415717,16618.293165,3780.726037,2020-21,7637.562733,9374.523538,3501.349412,2020-21,32444.336024,32825.296451,15473.835801
57,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#drop unneeded columsn
df1 = df.drop([2,3,4,5,6,8,9,10,12], axis = 1)
df1

                  1            7             11
0                NaN          NaN           NaN
1                NaN       4-year           NaN
2   All institutions          NaN           NaN
3               1963   243.335845   1010.793127
4               1968   321.002362   1417.128497
5               1969   358.354832   1561.856645
6               1970   393.688558   1706.297804
7               1971   427.761617   1832.157556
8               1972   502.630045   1948.308052
9               1973   513.576856   2044.526495
10              1974   512.416445   2130.384526
11              1975   542.145427   2291.253118
12              1976   616.551537   2534.024033
13              1977   654.680963   2700.299029
14              1978   687.674475   2957.923714
15              1979   737.548351   3225.038907
16              1980   803.747278   3616.835567
17              1981   909.499354   4113.319087
18              1982  1031.433165   4638.918917
19              1983  1147.727212   5092.950750
20              1984  1227.881695   5555.859459
21              1985  1317.601053   6120.558325
22              1986  1413.678767   6658.444594
23              1987  1537.368133   7116.105052
24              1988  1646.188102   7721.603549
25              1989  1779.609033   8396.328498
26              1990  1888.129113   9082.536420
27              1991  2116.892852   9759.443078
28              1992  2349.108575  10293.533165
29              1993  2536.582308  10952.218450
30              1994  2680.715293  11480.931134
31              1995  2847.579122  12243.156323
32              1996  2987.221282  12881.247323
33              1997  3109.505876  13344.249780
34              1998  3228.716855  13972.870964
35              1999  3348.805705  14616.047633
36              2000  3500.524982  15470.473798
37              2001  3735.205656  16210.886963
38              2002  4046.173101  16825.894536
39              2003  4586.540638  17763.195261
40              2004  5026.550249  18603.887093
41              2005  5350.929386  19291.662562
42              2006  5666.216013  20516.598712
43              2007  5943.137008  21426.674228
44              2008  6311.838371  22039.916813
45              2009  6716.599169  22269.293952
46              2010  7131.846567  22677.294091
47              2011  7713.410494  23463.672108
48              2012  8070.190026  24522.636955
49              2013  8311.861658  25706.763577
50              2014  8543.353275  26738.523395
51              2015  8778.397073  27941.604628
52              2016  8804.399324  29475.543676
53              2017  9036.059338  30722.613119
54              2018  9211.803768  31883.340470
55              2019  9349.141651  32763.973541
56              2020  9374.523538  32825.296451
57              2021          NaN           NaN

In [10]:
#drop unneeded rows
df2 = df1.drop(df1.index[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,57]])
df2

      1            7             11
23  1987  1537.368133   7116.105052
24  1988  1646.188102   7721.603549
25  1989  1779.609033   8396.328498
26  1990  1888.129113   9082.536420
27  1991  2116.892852   9759.443078
28  1992  2349.108575  10293.533165
29  1993  2536.582308  10952.218450
30  1994  2680.715293  11480.931134
31  1995  2847.579122  12243.156323
32  1996  2987.221282  12881.247323
33  1997  3109.505876  13344.249780
34  1998  3228.716855  13972.870964
35  1999  3348.805705  14616.047633
36  2000  3500.524982  15470.473798
37  2001  3735.205656  16210.886963
38  2002  4046.173101  16825.894536
39  2003  4586.540638  17763.195261
40  2004  5026.550249  18603.887093
41  2005  5350.929386  19291.662562
42  2006  5666.216013  20516.598712
43  2007  5943.137008  21426.674228
44  2008  6311.838371  22039.916813
45  2009  6716.599169  22269.293952
46  2010  7131.846567  22677.294091
47  2011  7713.410494  23463.672108
48  2012  8070.190026  24522.636955
49  2013  8311.861658  25706.763577
50  2014  8543.353275  26738.523395
51  2015  8778.397073  27941.604628
52  2016  8804.399324  29475.543676
53  2017  9036.059338  30722.613119
54  2018  9211.803768  31883.340470
55  2019  9349.141651  32763.973541
56  2020  9374.523538  32825.296451

In [11]:
df2.columns

Int64Index([1, 7, 11], dtype='int64')

In [16]:
df3 = df2.rename(columns = {1: 'year', 7: 'public', 11: 'private'})
df3

    year       public       private
23  1987  1537.368133   7116.105052
24  1988  1646.188102   7721.603549
25  1989  1779.609033   8396.328498
26  1990  1888.129113   9082.536420
27  1991  2116.892852   9759.443078
28  1992  2349.108575  10293.533165
29  1993  2536.582308  10952.218450
30  1994  2680.715293  11480.931134
31  1995  2847.579122  12243.156323
32  1996  2987.221282  12881.247323
33  1997  3109.505876  13344.249780
34  1998  3228.716855  13972.870964
35  1999  3348.805705  14616.047633
36  2000  3500.524982  15470.473798
37  2001  3735.205656  16210.886963
38  2002  4046.173101  16825.894536
39  2003  4586.540638  17763.195261
40  2004  5026.550249  18603.887093
41  2005  5350.929386  19291.662562
42  2006  5666.216013  20516.598712
43  2007  5943.137008  21426.674228
44  2008  6311.838371  22039.916813
45  2009  6716.599169  22269.293952
46  2010  7131.846567  22677.294091
47  2011  7713.410494  23463.672108
48  2012  8070.190026  24522.636955
49  2013  8311.861658  25706.763577
50  2014  8543.353275  26738.523395
51  2015  8778.397073  27941.604628
52  2016  8804.399324  29475.543676
53  2017  9036.059338  30722.613119
54  2018  9211.803768  31883.340470
55  2019  9349.141651  32763.973541
56  2020  9374.523538  32825.296451

In [17]:
df3.dtypes

year        object
public      object
private    float64
dtype: object

In [18]:
df4 = df3.astype({'public': 'float', 'private': 'float'})
df4.dtypes

year        object
public     float64
private    float64
dtype: object

In [19]:
df5 = df4.round(2)
df5

    year   public   private
23  1987  1537.37   7116.11
24  1988  1646.19   7721.60
25  1989  1779.61   8396.33
26  1990  1888.13   9082.54
27  1991  2116.89   9759.44
28  1992  2349.11  10293.53
29  1993  2536.58  10952.22
30  1994  2680.72  11480.93
31  1995  2847.58  12243.16
32  1996  2987.22  12881.25
33  1997  3109.51  13344.25
34  1998  3228.72  13972.87
35  1999  3348.81  14616.05
36  2000  3500.52  15470.47
37  2001  3735.21  16210.89
38  2002  4046.17  16825.89
39  2003  4586.54  17763.20
40  2004  5026.55  18603.89
41  2005  5350.93  19291.66
42  2006  5666.22  20516.60
43  2007  5943.14  21426.67
44  2008  6311.84  22039.92
45  2009  6716.60  22269.29
46  2010  7131.85  22677.29
47  2011  7713.41  23463.67
48  2012  8070.19  24522.64
49  2013  8311.86  25706.76
50  2014  8543.35  26738.52
51  2015  8778.40  27941.60
52  2016  8804.40  29475.54
53  2017  9036.06  30722.61
54  2018  9211.80  31883.34
55  2019  9349.14  32763.97
56  2020  9374.52  32825.30

In [20]:
df5.to_csv('Tuition_87.csv', index=False)